### ISSUE TITLE
'hasMore' error when using get_quote()

### ISSUE THREAD

**Issue by spencerrojahn** [tedchou12/webull#69] opened 2020-07-09 18:36 UTC
The KeyError 'hasMore' is printed out everytime I try to get quote information from a stock. It had worked perfectly fine for 2 months up until now. I'm not sure what that error means so I have no idea what the problem is. Is there a reason why get_quote() is doing this?

**Comment by qnguye** [comment] 2020-07-10 01:07
i'm having this same error with get_bars() too!! It was working 2 days ago and now every request stuck with this. Please help. Thanks

**Comment by cryptobull69** [comment] 2020-07-10 01:33
Duplicate of #68 

It looks like a fix might be already merged to master branch now.

**Closed** 2020-12-30 15:59 UTC
