### ISSUE TITLE
Login status to the paper trading account

### ISSUE THREAD

**Issue by aytoast** [tedchou12/webull#139] opened 2021-01-20 09:49 UTC
Hi Ted, 

This might be a very dumb question as I'm fairly new to Python working with API libraries, but I'm trying to fetch the account details of the paper trading account and I seem to get this error: `id = result[0]['id'] KeyError: 0` with the following code. 

`from webull import paper_webull`

`wb = paper_webull()`
`wb.login('test@test.com', 'pa$$w0rd')`
`wb.get_account_id()`
`print(wb.get_account())`

Does this mean that I didn't login sucessfully?
What does the trade_token do in this instance?

**Comment by tedchou12** [comment] 2021-01-20 10:07
No problem, seems like you are missing the get_mfa() call I think, this should help you:
https://www.youtube.com/watch?v=fqBOePxsCDQ

**Comment by tedchou12** [comment] 2021-01-24 12:39
@aytoast 
sorry, I found out this might be the root cause:
https://github.com/tedchou12/webull/pull/143

I have merged, could you try again and let me know?

**Closed** 2021-02-14 12:51 UTC
