### ISSUE TITLE
Issue with get_ticker() / hasMore variable

### ISSUE THREAD

**Issue by alphatrades4** [tedchou12/webull#49] opened 2020-05-28 17:35 UTC
>> Printed the response in the get_ticker() function. It checked for "hasMore" false and dies. The tickerId is still there in the list. Stock is SPLK as example

Started to see this issue.{'categoryId': 0, 'categoryName': '综合', 'hasMore': False, 'list': [{'tickerId': 913255699, 'exchangeId': 96, 'type': 2, 'secType': [61], 'regionId': 6, 'regionCode': 'US', 'currencyId': 247, 'name': 'Splunk', 'symbol': 'SPLK', 'disSymbol': 'SPLK', 'disExchangeCode': 'NASDAQ', 'exchangeCode': 'NSQ', 'listStatus': 1, 'template': 'stock', 'derivativeSupport': 1}]}

def get_ticker(self, stock=''):
        '''
        Lookup ticker_id
        '''
        ticker_id = 0
        if stock and isinstance(stock, str):
            response = requests.get(self._urls.stock_id(stock))
            result = response.json()
            **if result['hasMore'] == False:
                raise ValueError('TickerId could not be found for stock {}'.format(stock))**
            elif result['list']:
                for item in result['list']: # implies multiple tickers, but only assigns last one?
                    ticker_id = item['tickerId']
        else:
            raise ValueError('Stock symbol is required')
        return ticker_id

**Comment by timwelch** [comment] 2020-07-08 16:50
I think my post is a duplicate of this... 

https://github.com/tedchou12/webull/issues/66

**Comment by tedchou12** [comment] 2020-07-09 01:10
# implies multiple tickers, but only assigns last one?
Yes! That is right.
This is because webull seems to respond in a list to search for tickers.

**Comment by tedchou12** [comment] 2020-11-07 06:38
discussed in #83 
Fix would solve this problem

**Closed by tedchou12** 2020-11-07 06:38 UTC
